# 작업하는 자신의 경로에 맞게 수정필요
# 수정 후 파일이름 >>>  config.yaml  <<< 변경 후 저장
paths:
  model_path: "/your/path/to/model"
  chroma_db_path: "/your/path/to/chroma"
  processed_json_path: "/your/path/to/json"

api:
  host: "127.0.0.1"
  port: 9000
